spring:
  profiles:
    active:
    - dev

---
server:
  port: 80

spring:
  profiles: dev   #开发环境
  application:
    name: consumer-dept

feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

---
server:
  port: 81

spring:
  profiles: test   #开发环境
  application:
    name: consumer-dept

feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
# 请保存为UTF-8格式