spring:
  profiles:
    active:
    - dev

---
server:
  port: 7001      #注册中心占用7001端口，冒号后面必须要有空格
spring:
  profiles: dev   #开发环境
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: eureka7001.com #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eure-server自己不注册进服务列表中
    fetch-registry: false       #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
---
server:
  port: 7001      #注册中心占用7001端口，冒号后面必须要有空格
spring:
  profiles: test  #测试环境
  application:
    name: cloud-eureka-server
eureka:
  instance:
    hostname: eureka7001.com #冒号后面必须要有空格
  client:
    register-with-eureka: false #当前的eure-server自己不注册进服务列表中
    fetch-registry: false       #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
# 请保存为UTF-8格式